version: "3.8"

# Define the services
services:
  server:
    # based on upstream image
    image: razvanfv/docker-ui:server
    container_name: docker-ui-server
    hostname: docker_compose
    # where sample projects are located
    working_dir: /opt/docker-projects/
    ports:
      # <host>:<container>
      - "3000:3000"
    volumes:
      - ./server-side/docker-projects:/opt/docker-projects
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET=Thisismysecret
      - NODE_ENV=development
      - MONGO_DB_USERNAME=admin-user
      - MONGO_DB_PASSWORD=admin-password
      - MONGO_DB_HOST=database
      - MONGO_DB_PORT=
      - MONGO_DB_PARAMETERS=?authSource=admin
      - MONGO_DB_DATABASE=docker-ui
      - USING_DOCKER=true
    links:
      - database

  database:
    image: mongo # specify image to build container from
    container_name: docker-ui-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_DB_USERNAME=admin-user1
      - MONGO_DB_PASSWORD=admin-password1
      - MONGO_DB=docker-ui
    volumes:
      - ./mongo:/home/mongodb
      - ./mongo/init-db.d/:/docker-ui-entrypoint-init-db.d/
      - ./mongo/db:/data/db
    ports:
      - "27017:27017" # specify port forewarding


  client:
    image: razvanfv/docker-ui:client
    container_name: docker-ui-client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4200:4200" # <host>:<container>
    links:
      - server
