version: '3.3'

services:
  posio:
    image: l4rm4nd/posio:latest
    container_name: posio
    restart: unless-stopped
    ports:
      - 5000:5000/tcp
    expose:
      - 5000/tcp
    environment:
      - POSIO_SETTINGS=/app/posio/config.py
      - FLASK_APP=/app/posio/game_master.py
