/**
 * Model class that contains logic for handling a project.
 * The project is read from the docker-projects directory.
 */
class Project {
  /**
   * Creates a project
   * @param {string} id generated by parsing the name of the folder
   * that contains the project
   * @param {string} composeDir path to the folder that contains the
   * compose file
   * @param {string} composePath path to the compose file
   * @param {string} yaml contents of the compose file
   */
  constructor(id, composeDir, composePath, yaml) {
    this.id = id;
    this.composeDir = composeDir;
    this.composePath = composePath;
    this.yaml = yaml;
  }
}
export default Project;
